import { Product, ProductCategories, Farmer } from "@/types";
import image1 from "../../../public/images/beef.jpeg";
import image2 from "../../../public/images/beef2.jpeg";
import image3 from "../../../public/images/chesse1.jpeg";
import image4 from "../../../public/images/Tripe2.jpeg";
import image5 from "../../../public/images/Tripa.jpeg";
import image6 from "../../../public/images/chesse2.jpeg";
import image7 from "../../../public/images/chesse3.jpeg";
import image8 from "../../../public/images/chicken.jpeg";
import image9 from "../../../public/images/chicken2.jpeg";
import image0 from "../../../public/images/crabs2.jpeg";
// components/constants/reviews.ts
import { Review, ReviewStats } from "@/types";

export const sampleReviews: Review[] = [
  {
    id: 1,
    productId: 1,
    userId: 101,
    userName: "Chinwe Okoro",
    userAvatar: "/users/chinwe.jpg",
    rating: 5,
    title: "Excellent Quality Potatoes!",
    comment: "The potatoes were fresh, well-packaged, and exactly as described. They arrived on time and were perfect for making chips. Will definitely order again!",
    date: "2024-02-15",
    verifiedPurchase: true,
    helpfulCount: 24,
    reply: {
      id: 1,
      vendorName: "Mountain View Farm",
      comment: "Thank you for your wonderful review! We're glad you enjoyed our potatoes. We take pride in delivering fresh produce directly from our farm.",
      date: "2024-02-16",
    },
  },
  {
    id: 2,
    productId: 1,
    userId: 102,
    userName: "Ahmed Bello",
    userAvatar: "/users/ahmed.jpg",
    rating: 4,
    title: "Good but smaller than expected",
    comment: "Potatoes were fresh and tasty, but some were smaller than I expected based on the photos. Delivery was fast though.",
    date: "2024-02-10",
    verifiedPurchase: true,
    helpfulCount: 12,
  },
  {
    id: 3,
    productId: 1,
    userId: 103,
    userName: "Grace Williams",
    userAvatar: "/users/grace.jpg",
    rating: 5,
    comment: "Perfect for making mashed potatoes! Very fresh and clean. The vendor was responsive and answered all my questions.",
    date: "2024-02-05",
    verifiedPurchase: true,
    helpfulCount: 18,
  },
  {
    id: 4,
    productId: 1,
    userId: 104,
    userName: "Emeka Nwosu",
    userAvatar: "/users/emeka.jpg",
    rating: 3,
    title: "Average quality",
    comment: "Some potatoes had bruises and weren't as fresh as I'd hoped. They were still usable but not the best quality I've seen.",
    date: "2024-01-28",
    verifiedPurchase: true,
    helpfulCount: 5,
    reply: {
      id: 2,
      vendorName: "Mountain View Farm",
      comment: "We're sorry to hear about your experience. We've addressed this with our quality control team to ensure better sorting. Please contact us for a partial refund.",
      date: "2024-01-29",
    },
  },
  {
    id: 5,
    productId: 1,
    userId: 105,
    userName: "Fatima Yusuf",
    userAvatar: "/users/fatima.jpg",
    rating: 5,
    title: "Farm fresh potatoes!",
    comment: "These are genuinely farm-fresh potatoes. You can tell they were recently harvested. Great for roasting and baking.",
    date: "2024-01-20",
    verifiedPurchase: true,
    helpfulCount: 31,
  },
];

export const sampleReviewStats: ReviewStats = {
  averageRating: 4.4,
  totalReviews: 156,
  ratingCounts: {
    5: 89,
    4: 42,
    3: 18,
    2: 5,
    1: 2,
  },
};

export const products: Product[] = [
  {
    id: 1,
    name: "Farm Fresh Potatoes - Russet (10kg)",
    price: 15990,
    originalPrice: 18990,
    image: image1,
    rating: 4.0,
    reviewCount: 156,
    featured: false,
    inStock: true,
    stockCount: 45,
    organic: false,
    badge: "Fresh",
    description:
      "Premium Russet potatoes perfect for baking, frying, and mashing. Freshly harvested from our local farms.",
    tags: ["potatoes", "starchy", "versatile"],
    category: {
      id: "veg-1",
      name: "Vegetables",
      icon: "🥔",
    },
    images: [image1, image2],
    vendor: {
      phone: "0803 123 4567",
      id: 9,
      name: "Mountain View Farm",
      farmName: "Mountain View Farm",
      location: "Jos, Nigeria",
      rating: 4.8,
      reviewCount: 234,
      totalSales: "15K+ tons",
      certifications: ["Fresh Produce Certified", "Quality Standard"],
      specialties: [
        "Potatoes",
        "Onions",
        "Root Vegetables",
        "Seasonal Produce",
      ],
      avatar: "/farmers/mountain-view.jpg",
      isVerified: true,
      joinDate: "2018",
      responseRate: 96,
      deliveryTime: "48h",
    },
    location: "Jos, Plateau",
    condition: "Fresh",
    postedDate: "2 days ago",
    sellerYears: "5+ YEARS ON AGROFARM",
  },
  {
    id: 2,
    name: "Organic Apples - Red Delicious (3kg)",
    price: 9990,
    originalPrice: 11990,
    image: image2,
    rating: 4.0,
    reviewCount: 123,
    featured: true,
    inStock: true,
    stockCount: 32,
    organic: true,
    badge: "Organic",
    description:
      "Sweet and crisp organic Red Delicious apples. Perfect for snacking, baking, and salads.",
    tags: ["apples", "organic", "fruit", "sweet"],
    category: {
      id: "fruit-1",
      name: "Fruits",
      icon: "🍎",
    },
    images: [image1, image2],
    vendor: {
      phone: "0803 123 4567",
      id: 10,
      name: "Orchard Fresh",
      farmName: "Orchard Fresh",
      location: "Benue, Nigeria",
      rating: 4.9,
      reviewCount: 567,
      totalSales: "22K+ tons",
      certifications: ["Organic Certified", "Fruit Quality Standard"],
      specialties: ["Apples", "Pears", "Stone Fruits", "Organic Fruits"],
      avatar: "/farmers/orchard-fresh.jpg",
      isVerified: true,
      joinDate: "2019",
      responseRate: 98,
      deliveryTime: "24h",
    },
    location: "Jos, Plateau",
    condition: "Fresh",
    postedDate: "2 days ago",
    sellerYears: "5+ YEARS ON AGROFARM",
  },
  {
    id: 3,
    name: "Fresh Carrots - Organic (2kg)",
    price: 6490,
    originalPrice: 7490,
    image: image3,
    rating: 4.5,
    reviewCount: 89,
    featured: false,
    inStock: true,
    stockCount: 67,
    organic: true,
    badge: "Organic",
    description:
      "Sweet and crunchy organic carrots. Rich in vitamins and perfect for cooking or snacking.",
    tags: ["carrots", "organic", "root", "healthy"],
    category: {
      id: "veg-1",
      name: "Vegetables",
      icon: "🥕",
    },
    images: [image1, image2],
    vendor: {
      phone: "0803 123 4567",
      id: 1,
      name: "Ahmed Ibrahim",
      farmName: "Green Valley Farm",
      location: "Kaduna, Nigeria",
      rating: 4.9,
      reviewCount: 1240,
      totalSales: "25K+ tons",
      certifications: [
        "Certified Organic",
        "ISO 9001",
        "Food Safety Certified",
      ],
      specialties: [
        "Organic Vegetables",
        "Tomatoes",
        "Bell Peppers",
        "Cucumbers",
      ],
      avatar: "/farmers/ahmed.jpg",
      isVerified: true,
      joinDate: "2018",
      responseRate: 98,
      deliveryTime: "24-48h",
    },
    location: "Jos, Plateau",
    condition: "Fresh",
    postedDate: "2 days ago",
    sellerYears: "5+ YEARS ON AGROFARM",
  },
  {
    id: 4,
    name: "Cherry Tomatoes - Vine Ripened (1kg)",
    price: 8990,
    originalPrice: 9990,
    image: image4,
    rating: 4.8,
    reviewCount: 201,
    featured: true,
    inStock: true,
    stockCount: 28,
    organic: false,
    badge: "Fresh",
    description:
      "Sweet and juicy cherry tomatoes, vine-ripened for maximum flavor. Perfect for salads and cooking.",
    tags: ["tomatoes", "cherry", "sweet", "salad"],
    category: {
      id: "veg-1",
      name: "Vegetables",
      icon: "🍅",
    },
    images: [image1, image2],
    vendor: {
      id: 11,
      phone: "0803 123 4567",
      name: "Sunshine Gardens",
      farmName: "Sunshine Gardens",
      location: "Ogun, Nigeria",
      rating: 4.9,
      reviewCount: 445,
      totalSales: "18K+ tons",
      certifications: ["Fresh Vegetables", "Quality Assured"],
      specialties: [
        "Tomatoes",
        "Cherry Tomatoes",
        "Vegetables",
        "Fresh Produce",
      ],
      avatar: "/farmers/sunshine-gardens.jpg",
      isVerified: true,
      joinDate: "2020",
      responseRate: 97,
      deliveryTime: "24h",
    },
    location: "Jos, Plateau",
    condition: "Fresh",
    postedDate: "2 days ago",
    sellerYears: "5+ YEARS ON AGROFARM",
  },
  {
    id: 5,
    name: "Sweet Corn - Fresh Picked (6 ears)",
    price: 5990,
    originalPrice: 6990,
    image: image5,
    rating: 4.3,
    reviewCount: 67,
    featured: false,
    inStock: true,
    stockCount: 53,
    organic: false,
    badge: "Sweet",
    description:
      "Freshly picked sweet corn with exceptional flavor. Great for boiling, grilling, or roasting.",
    tags: ["corn", "sweet", "grill", "summer"],
    category: {
      id: "veg-1",
      name: "Vegetables",
      icon: "🌽",
    },
    images: [image1, image2],
    vendor: {
      phone: "0803 123 4567",
      id: 12,
      name: "Harvest Moon Farm",
      farmName: "Harvest Moon Farm",
      location: "Kaduna, Nigeria",
      rating: 4.6,
      reviewCount: 178,
      totalSales: "12K+ tons",
      certifications: ["Fresh Corn", "Quality Standard"],
      specialties: ["Sweet Corn", "Maize", "Grains", "Seasonal Vegetables"],
      avatar: "/farmers/harvest-moon.jpg",
      isVerified: true,
      joinDate: "2019",
      responseRate: 94,
      deliveryTime: "48h",
    },
    location: "Jos, Plateau",
    condition: "Fresh",
    postedDate: "2 days ago",
    sellerYears: "5+ YEARS ON AGROFARM",
  },
  {
    id: 6,
    name: "Organic Spinach - Baby Leaves (500g)",
    price: 4990,
    originalPrice: 5990,
    image: image6,
    rating: 4.6,
    reviewCount: 143,
    featured: false,
    inStock: true,
    stockCount: 41,
    organic: true,
    badge: "Organic",
    description:
      "Tender organic baby spinach leaves. Perfect for salads, smoothies, and healthy cooking.",
    tags: ["spinach", "organic", "leafy", "healthy"],
    category: {
      id: "veg-1",
      name: "Vegetables",
      icon: "🥬",
    },
    images: [image1, image2],
    vendor: {
      phone: "0803 123 4567",
      id: 13,
      name: "Leafy Greens Co.",
      farmName: "Leafy Greens Co.",
      location: "Oyo, Nigeria",
      rating: 4.8,
      reviewCount: 289,
      totalSales: "10K+ tons",
      certifications: ["Organic Certified", "Leafy Greens Specialist"],
      specialties: ["Spinach", "Kale", "Lettuce", "Leafy Vegetables"],
      avatar: "/farmers/leafy-greens.jpg",
      isVerified: true,
      joinDate: "2020",
      responseRate: 95,
      deliveryTime: "24h",
    },
    location: "Jos, Plateau",
    condition: "Fresh",
    postedDate: "2 days ago",
    sellerYears: "5+ YEARS ON AGROFARM",
  },
  {
    id: 7,
    name: "Bell Peppers - Mixed Colors (1.5kg)",
    price: 7490,
    originalPrice: 8490,
    image: image7,
    rating: 4.4,
    reviewCount: 112,
    featured: true,
    inStock: true,
    stockCount: 36,
    organic: false,
    badge: "Colorful",
    description:
      "Vibrant mixed bell peppers in red, yellow, and green. Sweet and crunchy for various dishes.",
    tags: ["peppers", "bell", "colorful", "sweet"],
    category: {
      id: "veg-1",
      name: "Vegetables",
      icon: "🫑",
    },
    images: [image1, image2],
    vendor: {
      phone: "0803 123 4567",
      id: 14,
      name: "Rainbow Harvest",
      farmName: "Rainbow Harvest",
      location: "Plateau, Nigeria",
      rating: 4.7,
      reviewCount: 356,
      totalSales: "16K+ tons",
      certifications: ["Colorful Vegetables", "Fresh Produce"],
      specialties: [
        "Bell Peppers",
        "Colorful Vegetables",
        "Mixed Peppers",
        "Fresh Produce",
      ],
      avatar: "/farmers/rainbow-harvest.jpg",
      isVerified: true,
      joinDate: "2018",
      responseRate: 96,
      deliveryTime: "48h",
    },
    location: "Jos, Plateau",
    condition: "Fresh",
    postedDate: "2 days ago",
    sellerYears: "5+ YEARS ON AGROFARM",
  },
  {
    id: 8,
    name: "Fresh Broccoli - Crown Cut (1kg)",
    price: 5490,
    originalPrice: 6490,
    image: image8,
    rating: 4.2,
    reviewCount: 78,
    featured: false,
    inStock: true,
    stockCount: 59,
    organic: false,
    badge: "Fresh",
    description:
      "Fresh broccoli crowns with tight florets. Rich in nutrients and perfect for steaming or stir-fry.",
    tags: ["broccoli", "fresh", "healthy", "green"],
    category: {
      id: "veg-1",
      name: "Vegetables",
      icon: "🥦",
    },
    images: [image1, image2],
    vendor: {
      phone: "0803 123 4567",
      id: 1,
      name: "Ahmed Ibrahim",
      farmName: "Green Valley Farm",
      location: "Kaduna, Nigeria",
      rating: 4.9,
      reviewCount: 1240,
      totalSales: "25K+ tons",
      certifications: [
        "Certified Organic",
        "ISO 9001",
        "Food Safety Certified",
      ],
      specialties: [
        "Organic Vegetables",
        "Tomatoes",
        "Bell Peppers",
        "Cucumbers",
      ],
      avatar: "/farmers/ahmed.jpg",
      isVerified: true,
      joinDate: "2018",
      responseRate: 98,
      deliveryTime: "24-48h",
    },
    location: "Jos, Plateau",
    condition: "Fresh",
    postedDate: "2 days ago",
    sellerYears: "5+ YEARS ON AGROFARM",
  },
  {
    id: 9,
    name: "Organic Strawberries - Sweet (500g)",
    price: 12990,
    originalPrice: 14990,
    image: image9,
    rating: 4.9,
    reviewCount: 267,
    featured: true,
    inStock: true,
    stockCount: 24,
    organic: true,
    badge: "Organic",
    description:
      "Sweet and juicy organic strawberries. Perfect for desserts, smoothies, or fresh eating.",
    tags: ["strawberries", "organic", "sweet", "berries"],
    category: {
      id: "fruit-1",
      name: "Fruits",
      icon: "🍓",
    },
    images: [image1, image2],
    vendor: {
      id: 4,
      phone: "0803 123 4567",
      name: "Grace Williams",
      farmName: "Berry Best Farms",
      location: "Plateau, Nigeria",
      rating: 4.9,
      reviewCount: 543,
      totalSales: "12K+ tons",
      certifications: ["Organic Certified", "Fresh Produce"],
      specialties: ["Strawberries", "Raspberries", "Blueberries", "Fruits"],
      avatar: "/farmers/grace.jpg",
      isVerified: true,
      joinDate: "2020",
      responseRate: 96,
      deliveryTime: "24h",
    },
    location: "Jos, Plateau",
    condition: "Fresh",
    postedDate: "2 days ago",
    sellerYears: "5+ YEARS ON AGROFARM",
  },
  {
    id: 10,
    name: "Yellow Onions - Fresh (2kg)",
    price: 4490,
    originalPrice: 5490,
    image: image0,
    rating: 4.1,
    reviewCount: 94,
    featured: false,
    inStock: true,
    stockCount: 72,
    organic: false,
    badge: "Fresh",
    description:
      "Fresh yellow onions with strong flavor. Essential for cooking, soups, and various dishes.",
    tags: ["onions", "yellow", "cooking", "aromatic"],
    category: {
      id: "veg-1",
      name: "Vegetables",
      icon: "🧅",
    },
    images: [image1, image2],
    vendor: {
      phone: "0803 123 4567",
      id: 9,
      name: "Mountain View Farm",
      farmName: "Mountain View Farm",
      location: "Jos, Nigeria",
      rating: 4.8,
      reviewCount: 234,
      totalSales: "15K+ tons",
      certifications: ["Fresh Produce Certified", "Quality Standard"],
      specialties: [
        "Potatoes",
        "Onions",
        "Root Vegetables",
        "Seasonal Produce",
      ],
      avatar: "/farmers/mountain-view.jpg",
      isVerified: true,
      joinDate: "2018",
      responseRate: 96,
      deliveryTime: "48h",
    },
    location: "Jos, Plateau",
    condition: "Fresh",
    postedDate: "2 days ago",
    sellerYears: "5+ YEARS ON AGROFARM",
  },
];

export const productCategories: ProductCategories[] = [
  {
    id: "fruits",
    label: "Fruits",
    icon: "🍎",
  },
  {
    id: "vegetables",
    label: "Vegetables",
    icon: "🥕",
  },
  {
    id: "dairy",
    label: "Dairy & Eggs",
    icon: "🥛",
  },
  {
    id: "meat",
    label: "Meat & Poultry",
    icon: "🥩",
  },
  {
    id: "seafood",
    label: "Seafood",
    icon: "🐟",
  },
  {
    id: "bakery",
    label: "Bakery",
    icon: "🍞",
  },
  {
    id: "grains",
    label: "Grains & Pasta",
    icon: "🌾",
  },
  {
    id: "snacks",
    label: "Snacks",
    icon: "🍿",
  },
  {
    id: "beverages",
    label: "Beverages",
    icon: "🥤",
  },
  {
    id: "frozen",
    label: "Frozen Foods",
    icon: "🧊",
  },
  {
    id: "organic",
    label: "Organic",
    icon: "🌱",
  },
  {
    id: "pantry",
    label: "Pantry Staples",
    icon: "🥫",
  },
];

export const farmers: Farmer[] = [
  {
    id: 1,
    name: "Ahmed Ibrahim",
    farmName: "Green Valley Farm",
    location: "Kaduna, Nigeria",
    rating: 4.9,
    reviewCount: 1240,
    totalSales: "25K+ tons",
    certifications: ["Certified Organic", "ISO 9001", "Food Safety Certified"],
    specialties: [
      "Organic Vegetables",
      "Tomatoes",
      "Bell Peppers",
      "Cucumbers",
    ],
    avatar: "/farmers/ahmed.jpg",
    isVerified: true,
    joinDate: "2018",
    responseRate: 98,
    deliveryTime: "24-48h",
    phone: "0803 123 4567",
  },
  {
    id: 2,
    name: "Chinwe Okoro",
    farmName: "Fresh Harvest Gardens",
    location: "Ogun, Nigeria",
    rating: 4.8,
    reviewCount: 856,
    totalSales: "18K+ tons",
    certifications: ["Organic Certified", "GlobalG.A.P."],
    specialties: ["Leafy Greens", "Spinach", "Lettuce", "Kale"],
    avatar: "/farmers/chinwe.jpg",
    isVerified: true,
    joinDate: "2019",
    responseRate: 95,
    deliveryTime: "24h",
    phone: "0803 123 4567",
  },
  {
    id: 3,
    name: "Mohammed Bello",
    farmName: "Golden Grains Farm",
    location: "Kano, Nigeria",
    rating: 4.7,
    reviewCount: 672,
    totalSales: "32K+ tons",
    certifications: ["Grains Certified", "Quality Assured"],
    specialties: ["Rice", "Maize", "Wheat", "Millet"],
    avatar: "/farmers/mohammed.jpg",
    isVerified: true,
    joinDate: "2017",
    responseRate: 92,
    deliveryTime: "48-72h",
    phone:"234 9078637352"
  },
  {
    id: 4,
    name: "Grace Williams",
    farmName: "Berry Best Farms",
    location: "Plateau, Nigeria",
    rating: 4.9,
    reviewCount: 543,
    totalSales: "12K+ tons",
    certifications: ["Organic Certified", "Fresh Produce"],
    specialties: ["Strawberries", "Raspberries", "Blueberries", "Fruits"],
    avatar: "/farmers/grace.jpg",
    isVerified: true,
    joinDate: "2020",
    responseRate: 96,
    deliveryTime: "24h",
    phone: "0803 123 4567",
  },
  {
    id: 5,
    name: "Emeka Nwosu",
    farmName: "Tropical Fruits Plantation",
    location: "Enugu, Nigeria",
    rating: 4.6,
    reviewCount: 421,
    totalSales: "15K+ tons",
    certifications: ["Fresh Fruits", "Export Quality"],
    specialties: ["Mangoes", "Pineapples", "Oranges", "Bananas"],
    avatar: "/farmers/emeka.jpg",
    isVerified: true,
    joinDate: "2019",
    responseRate: 90,
    deliveryTime: "48h",
    phone: "0803 123 4567",
  },
  {
    id: 6,
    name: "Fatima Yusuf",
    farmName: "Organic Roots Farm",
    location: "Sokoto, Nigeria",
    rating: 4.8,
    reviewCount: 389,
    totalSales: "8K+ tons",
    certifications: ["100% Organic", "Soil Association"],
    specialties: ["Root Vegetables", "Carrots", "Potatoes", "Onions"],
    avatar: "/farmers/fatima.jpg",
    isVerified: true,
    joinDate: "2021",
    responseRate: 94,
    deliveryTime: "72h",
    phone: "0803 123 4567",
  },
  {
    id: 7,
    name: "David Johnson",
    farmName: "Poultry Masters",
    location: "Oyo, Nigeria",
    rating: 4.7,
    reviewCount: 678,
    totalSales: "50K+ birds",
    certifications: ["Animal Welfare", "HACCP Certified"],
    specialties: ["Chicken", "Eggs", "Turkey", "Duck"],
    avatar: "/farmers/david.jpg",
    isVerified: true,
    joinDate: "2016",
    responseRate: 97,
    deliveryTime: "24h",
    phone: "0803 123 4567",
  },
  {
    id: 8,
    name: "Aisha Mohammed",
    farmName: "Dairy Delight Farm",
    location: "Adamawa, Nigeria",
    rating: 4.9,
    reviewCount: 312,
    totalSales: "20K+ liters",
    certifications: ["Dairy Safe", "Quality Milk"],
    specialties: ["Fresh Milk", "Yogurt", "Cheese", "Butter"],
    avatar: "/farmers/aisha.jpg",
    isVerified: true,
    joinDate: "2020",
    responseRate: 93,
    deliveryTime: "48h",
    phone: "0803 123 4567",
  },
  // Additional farmers to match your products
  {
    id: 9,
    name: "Mountain View Farm",
    farmName: "Mountain View Farm",
    location: "Jos, Nigeria",
    rating: 4.8,
    reviewCount: 234,
    totalSales: "15K+ tons",
    certifications: ["Fresh Produce Certified", "Quality Standard"],
    specialties: ["Potatoes", "Onions", "Root Vegetables", "Seasonal Produce"],
    avatar: "/farmers/mountain-view.jpg",
    isVerified: true,
    joinDate: "2018",
    responseRate: 96,
    deliveryTime: "48h",
    phone: "0803 123 4567",
  },
  {
    id: 10,
    name: "Orchard Fresh",
    farmName: "Orchard Fresh",
    location: "Benue, Nigeria",
    rating: 4.9,
    reviewCount: 567,
    totalSales: "22K+ tons",
    certifications: ["Organic Certified", "Fruit Quality Standard"],
    specialties: ["Apples", "Pears", "Stone Fruits", "Organic Fruits"],
    avatar: "/farmers/orchard-fresh.jpg",
    isVerified: true,
    joinDate: "2019",
    responseRate: 98,
    deliveryTime: "24h",
    phone: "0803 123 4567",
  },
  {
    id: 11,
    name: "Sunshine Gardens",
    farmName: "Sunshine Gardens",
    location: "Ogun, Nigeria",
    rating: 4.9,
    reviewCount: 445,
    totalSales: "18K+ tons",
    certifications: ["Fresh Vegetables", "Quality Assured"],
    specialties: ["Tomatoes", "Cherry Tomatoes", "Vegetables", "Fresh Produce"],
    avatar: "/farmers/sunshine-gardens.jpg",
    isVerified: true,
    joinDate: "2020",
    responseRate: 97,
    deliveryTime: "24h",
    phone: "0803 123 4567",
  },
  {
    id: 12,
    name: "Harvest Moon Farm",
    farmName: "Harvest Moon Farm",
    location: "Kaduna, Nigeria",
    rating: 4.6,
    reviewCount: 178,
    totalSales: "12K+ tons",
    certifications: ["Fresh Corn", "Quality Standard"],
    specialties: ["Sweet Corn", "Maize", "Grains", "Seasonal Vegetables"],
    avatar: "/farmers/harvest-moon.jpg",
    isVerified: true,
    joinDate: "2019",
    responseRate: 94,
    deliveryTime: "48h",
    phone: "0803 123 4567",
  },
  {
    id: 13,
    name: "Leafy Greens Co.",
    farmName: "Leafy Greens Co.",
    location: "Oyo, Nigeria",
    rating: 4.8,
    reviewCount: 289,
    totalSales: "10K+ tons",
    certifications: ["Organic Certified", "Leafy Greens Specialist"],
    specialties: ["Spinach", "Kale", "Lettuce", "Leafy Vegetables"],
    avatar: "/farmers/leafy-greens.jpg",
    isVerified: true,
    joinDate: "2020",
    responseRate: 95,
    deliveryTime: "24h",
    phone: "0803 123 4567",
  },
  {
    id: 14,
    name: "Rainbow Harvest",
    farmName: "Rainbow Harvest",
    location: "Plateau, Nigeria",
    rating: 4.7,
    reviewCount: 356,
    totalSales: "16K+ tons",
    certifications: ["Colorful Vegetables", "Fresh Produce"],
    specialties: [
      "Bell Peppers",
      "Colorful Vegetables",
      "Mixed Peppers",
      "Fresh Produce",
    ],
    avatar: "/farmers/rainbow-harvest.jpg",
    isVerified: true,
    joinDate: "2018",
    responseRate: 96,
    deliveryTime: "48h",
    phone: "0803 123 4567",
  },
];
